YouTubeRestAPI/Controllers/JobListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace YouTubeRestAPI.Controllers
{
    public class JobListController : Controller
    {
        // GET: JobList
        public ActionResult Index(string status, int page = 1)
        {
            ViewBag.status = status;
            ViewBag.page = page;
            int limit = 40;
            int offset = (page - 1) * limit;

            List<Models.PostJob> jobList = new YouTubeDBIO().getJobs(offset, limit, status);
            if (jobList == null)
            {
                jobList = new List<Models.PostJob>();
                jobList.Add(new Models.PostJob() { job_error_description = "Error retrieving Jobs" });
            }

            Response.AddHeader("Refresh", "15");

            return View(jobList);
        }

        // GET: JobList/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: JobList/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: JobList/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: JobList/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: JobList/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: JobList/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: JobList/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

YouTubeRestAPI/Views/Shared/_Layout.cshtml
@{
    if (ViewBag.page == null) { ViewBag.page = 1; }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="container-fluid">
        <h1>YouTube Render Service JobList</h1>
    </div>
    <hr />
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="btn-group">
                @Html.ActionLink("All", "Index", "JobList", new { page = 1 }, new { @class = "btn btn-primary", id = "all" })
                @Html.ActionLink("Created", "Index", "JobList", new { status = "created", page = 1 }, new { @class = "btn btn-primary", id = "created" })
                @Html.ActionLink("Running", "Index", "JobList", new { status = "running", page = 1 }, new { @class = "btn btn-primary", id = "running" })
                @Html.ActionLink("Failed", "Index", "JobList", new { status = "failed", page = 1 }, new { @class = "btn btn-primary", id = "failed" })
                @Html.ActionLink("Finished", "Index", "JobList", new { status = "finished", page = 1 }, new { @class = "btn btn-primary", id = "finished" })
            </div>
            <div class="btn-group">
                @Html.ActionLink("Prev", "Index", "JobList", new { status = ViewBag.status, page = Math.Max(ViewBag.page - 1, 1) }, new { @class = "btn btn-primary" })
                <button class="btn btn-secondary" disabled>@ViewBag.page</button>
                @Html.ActionLink("Next", "Index", "JobList", new { status = ViewBag.status, page = ViewBag.page + 1 }, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>